// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.4
//   protoc               v5.29.0
// source: proto/transaction.proto

/* eslint-disable */

export const protobufPackage = "";

export const _PACKAGE_NAME = "";
